fix

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -24,6 +24,18 @@ jobs:
       - name: Build
         run: make build
 
+      - name: Test
+        run: make test
+
+      - name: Coverage
+        run: |
+          coverage=$(go tool cover -func=coverage.out | grep "total:" | awk '{print substr($3, 1, length($3)-1)}')
+          echo "Total coverage: $coverage%"
+          if (( $(echo "$coverage < 30.0" | bc -l) )); then
+            echo "Code coverage is below 80%, failing..."
+            exit 1
+          fi
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
 
